// cards from antiquities http://mtgimage.com/zip/ATQ.zip
// stats from http://www.crystalkeep.com/magic/products/antiquities.php
// specs from http://archive.wizards.com/magic/generic/cardlists/Antiquities_Checklist.txt
// - remove artist
// - s/^(.*?)  +(..)$/{name: "\1", stat: "\2"},/
// - turn lower-case
// - replace some lands with 1,2,3,4
// - replace "rack, the" with "the rack" 
// - remove ":"
var cards = [
{name: "amulet of kroog", stat: "c4"},
{name: "armageddon clock", stat: "u2"},
{name: "ashnod's altar", stat: "u2"},
{name: "ashnod's battle gear", stat: "u2"},
{name: "ashnod's transmogrant", stat: "u3"},
{name: "battering ram", stat: "c4"},
{name: "bronze tablet", stat: "u1"},
{name: "candelabra of tawnos", stat: "u1"},
{name: "clay statue", stat: "c4"},
{name: "clockwork avian", stat: "u1"},
{name: "colossus of sardia", stat: "u1"},
{name: "coral helm", stat: "u1"},
{name: "cursed rack", stat: "c1"},
{name: "dragon engine", stat: "c4"},
{name: "feldon's cane", stat: "c1"},
{name: "golgothian sylex", stat: "u1"},
{name: "grapeshot catapult", stat: "c4"},
{name: "ivory tower", stat: "u3"},
{name: "jalum tome", stat: "u2"},
{name: "mightstone", stat: "u3"},
{name: "millstone", stat: "u3"},
{name: "mishra's war machine", stat: "u1"},
{name: "obelisk of undoing", stat: "u1"},
{name: "onulet", stat: "u3"},
{name: "ornithopter", stat: "c4"},
{name: "primal clay", stat: "u3"},
{name: "the rack", stat: "u3"},
{name: "rakalite", stat: "u3"},
{name: "rocket launcher", stat: "u3"},
{name: "shapeshifter", stat: "u1"},
{name: "staff of zegon", stat: "c4"},
{name: "su-chi", stat: "u3"},
{name: "tablet of epityr", stat: "c4"},
{name: "tawnos's coffin", stat: "u1"},
{name: "tawnos's wand", stat: "u3"},
{name: "tawnos's weaponry", stat: "u3"},
{name: "tetravus", stat: "u1"},
{name: "triskelion", stat: "u1"},
{name: "urza's avenger", stat: "u1"},
{name: "urza's chalice", stat: "c4"},
{name: "urza's miter", stat: "u1"},
{name: "wall of spears", stat: "u3"},
{name: "weakstone", stat: "u3"},
{name: "yotian soldier", stat: "c4"},
{name: "artifact possession", stat: "c4"},
{name: "gate to phyrexia", stat: "u3"},
{name: "haunting wind", stat: "u3"},
{name: "phyrexian gremlins", stat: "c4"},
{name: "priest of yawgmoth", stat: "c4"},
{name: "xenic poltergeist", stat: "u3"},
{name: "yawgmoth demon", stat: "u1"},
{name: "drafna's restoration", stat: "c4"},
{name: "energy flux", stat: "u3"},
{name: "hurkyl's recall", stat: "u1"},
{name: "power artifact", stat: "u3"},
{name: "reconstruction", stat: "c4"},
{name: "sage of lat-nam", stat: "c4"},
{name: "transmute artifact", stat: "u3"},
{name: "argothian pixies", stat: "c4"},
{name: "argothian treefolk", stat: "c4"},
{name: "citanul druid", stat: "u3"},
{name: "crumble", stat: "c4"},
{name: "gaea's avenger", stat: "u1"},
{name: "powerleech", stat: "u3"},
{name: "titania's song", stat: "u3"},
{name: "mishra's factory1", stat: "u1"},
{name: "mishra's factory2", stat: "c1"},
{name: "mishra's factory3", stat: "u1"},
{name: "mishra's factory4", stat: "u1"},
{name: "mishra's workshop", stat: "u1"},
{name: "strip mine1", stat: "u1"},
{name: "strip mine2", stat: "u1"},
{name: "strip mine3", stat: "c1"},
{name: "strip mine4", stat: "u1"},
{name: "urza's mine1", stat: "c2"},
{name: "urza's mine2", stat: "c1"},
{name: "urza's mine3", stat: "c1"},
{name: "urza's mine4", stat: "c2"},
{name: "urza's power plant1", stat: "c2"},
{name: "urza's power plant2", stat: "c1"},
{name: "urza's power plant3", stat: "c1"},
{name: "urza's power plant4", stat: "c2"},
{name: "urza's tower1", stat: "c2"},
{name: "urza's tower2", stat: "c1"},
{name: "urza's tower3", stat: "c1"},
{name: "urza's tower4", stat: "c1"},
{name: "artifact blast", stat: "c4"},
{name: "atog", stat: "c4"},
{name: "detonate", stat: "u3"},
{name: "dwarven weaponsmith", stat: "u3"},
{name: "goblin artisans", stat: "u3"},
{name: "orcish mechanics", stat: "c4"},
{name: "shatterstorm", stat: "u1"},
{name: "argivian archaeologist", stat: "u1"},
{name: "argivian blacksmith", stat: "c4"},
{name: "artifact ward", stat: "c4"},
{name: "circle of protection artifacts", stat: "u3"},
{name: "damping field", stat: "u3"},
{name: "martyrs of korlis", stat: "u3"},
{name: "reverse polarity", stat: "c4"}
];

var booster = 8;
var boosterRare = 0;
var boosterUncommon = 2;
var boosterCommon = 6;

var setFolder = "ATQ";