// cards from thedark http://mtgimage.com/zip/DRK.zip
// stats from http://www.crystalkeep.com/magic/products/thedark.php
// specs from http://archive.wizards.com/magic/generic/cardlists/Arabian_Nights_Checklist.txt
// - remove artist
// - s/^(.*?)  +(..)$/{name: "\1", stat: "\2"},/
// - turn lower-case
// - replace " (a)" with "1"
// - replace " (b)" with "2"
// - replace áúâí with auai
// - fix a few "'"
var cards = [
{name: "ashes to ashes", stat: "c3"},
{name: "banshee", stat: "u2"},
{name: "bog imp", stat: "c3"},
{name: "bog rats", stat: "c3"},
{name: "curse artifact", stat: "u2"},
{name: "eater of the dead", stat: "u2"},
{name: "the fallen", stat: "u2"},
{name: "frankenstein's monster", stat: "u1"},
{name: "grave robbers", stat: "u1"},
{name: "inquisition", stat: "c3"},
{name: "marsh gas", stat: "c3"},
{name: "murk dwellers", stat: "c3"},
{name: "nameless race", stat: "u1"},
{name: "rag man", stat: "u1"},
{name: "season of the witch", stat: "u1"},
{name: "uncle istvan", stat: "u2"},
{name: "word of binding", stat: "c3"},
{name: "worms of the earth", stat: "u1"},
{name: "amnesia", stat: "u2"},
{name: "apprentice wizard", stat: "u1"},
{name: "dance of many", stat: "u1"},
{name: "deep water", stat: "c3"},
{name: "drowned", stat: "c3"},
{name: "electric eel", stat: "u2"},
{name: "erosion", stat: "c3"},
{name: "flood", stat: "u2"},
{name: "ghost ship", stat: "c3"},
{name: "giant shark", stat: "c3"},
{name: "leviathan", stat: "u1"},
{name: "mana vortex", stat: "u1"},
{name: "merfolk assassin", stat: "u2"},
{name: "mind bomb", stat: "u1"},
{name: "psychic allergy", stat: "u1"},
{name: "riptide", stat: "c3"},
{name: "sunken city", stat: "c3"},
{name: "tangle kelp", stat: "u2"},
{name: "water wurm", stat: "c3"},
{name: "carnivorous plant", stat: "c3"},
{name: "elves of deep shadow", stat: "u2"},
{name: "gaea's touch", stat: "c3"},
{name: "hidden path", stat: "u1"},
{name: "land leeches", stat: "c3"},
{name: "lurker", stat: "u1"},
{name: "marsh viper", stat: "c3"},
{name: "niall silvain", stat: "u1"},
{name: "people of the woods", stat: "u2"},
{name: "savaen elves", stat: "c3"},
{name: "scarwood bandits", stat: "u1"},
{name: "scarwood hag", stat: "u2"},
{name: "scavenger folk", stat: "c3"},
{name: "spitting slug", stat: "u2"},
{name: "tracker", stat: "u1"},
{name: "venom", stat: "c3"},
{name: "whippoorwill", stat: "u2"},
{name: "wormwood treefolk", stat: "u1"},
{name: "ball lightning", stat: "u1"},
{name: "blood moon", stat: "u1"},
{name: "brothers of fire", stat: "u2"},
{name: "cave people", stat: "u2"},
{name: "eternal flame", stat: "u1"},
{name: "fire drake", stat: "u2"},
{name: "fissure", stat: "c3"},
{name: "goblin caves", stat: "c3"},
{name: "goblin digging team", stat: "c3"},
{name: "goblin hero", stat: "c3"},
{name: "goblin rock sled", stat: "c3"},
{name: "goblin shrine", stat: "c3"},
{name: "goblin wizard", stat: "u1"},
{name: "goblins of the flarg", stat: "c3"},
{name: "inferno", stat: "u1"},
{name: "mana clash", stat: "u1"},
{name: "orc general", stat: "u2"},
{name: "sisters of the flame", stat: "u2"},
{name: "angry mob", stat: "u2"},
{name: "blood of the martyr", stat: "u2"},
{name: "brainwash", stat: "c3"},
{name: "cleansing", stat: "u1"},
{name: "dust to dust", stat: "c3"},
{name: "exorcist", stat: "u1"},
{name: "fasting", stat: "u2"},
{name: "festival", stat: "c3"},
{name: "fire and brimstone", stat: "u2"},
{name: "holy light", stat: "c3"},
{name: "knights of thorn", stat: "u1"},
{name: "martyr's cry", stat: "u1"},
{name: "miracle worker", stat: "c3"},
{name: "morale", stat: "c3"},
{name: "pikemen", stat: "c3"},
{name: "preacher", stat: "u1"},
{name: "squire", stat: "c3"},
{name: "tivadar's crusade", stat: "u2"},
{name: "witch hunter", stat: "u1"},
{name: "barl's cage", stat: "u1"},
{name: "bone flute", stat: "u2"},
{name: "book of rass", stat: "u2"},
{name: "coal golem", stat: "u2"},
{name: "dark sphere", stat: "u2"},
{name: "diabolic machine", stat: "u2"},
{name: "fellwar stone", stat: "u2"},
{name: "fountain of youth", stat: "u2"},
{name: "living armor", stat: "u2"},
{name: "necropolis", stat: "u2"},
{name: "reflecting mirror", stat: "u2"},
{name: "runesword", stat: "u2"},
{name: "scarecrow", stat: "u2"},
{name: "skull of orm", stat: "u2"},
{name: "standing stones", stat: "u2"},
{name: "stone calendar", stat: "u1"},
{name: "tormod's crypt", stat: "u2"},
{name: "tower of coireall", stat: "u2"},
{name: "wand of ith", stat: "u2"},
{name: "war barge", stat: "u2"},
{name: "city of shadows", stat: "u1"},
{name: "maze of ith", stat: "c1"},
{name: "safe haven", stat: "u1"},
{name: "sorrow's path", stat: "u1"},
{name: "dark heart of the wood", stat: "c3"},
{name: "marsh goblins", stat: "c3"},
{name: "scarwood goblins", stat: "c3"},
];

var booster = 8;
var boosterRare = 0;
var boosterUncommon = 2;
var boosterCommon = 6;

var setFolder = "DRK";